- name: prepare raspberry for time machine enabled samba
  hosts: pi
  # vars:
    # come from inventory eg.
    # mountSrc: /dev/sda1
    # The users will be created if they do not exist already, but they will have to have their passwords set
    #users:
    #- pi

  roles:
  # partition and format the backup hard drive to ext4
  # - partition
  - time-machine
