- name: prepare raspberry for time machine enabled samba
  hosts: pi
  vars:
    # UUID of target disk (use blkid to find out)
    # uuid: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
    # UUID of target partition (use blkid to find out)
    # partuuid: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
    # The users will be created if they do not exist already, but they will have to have their passwords set
    #users:
    #- pi

  roles:
  - time-machine
