- parted:
    device: "{{ partitionDevice }}"
    state: present
    label: gpt
    fs_type: ext4
    number: 1
  name: "Ensuring backup parition"

- filesystem:
    dev: "{{ partitionDevice }}1"
    fstype: ext4
    resizefs: yes
  name: "Ensuring ext4 filesystem"
