- parted:
    device: "{{ partitionDevice }}"
    unit: MiB
  register: info
  name: "Getting partition info"

- pause:
    prompt: "Do you want to repartition {{ partitionDevice }} (yes/no)?"
    register: repartition_device
    delegate_to: localhost

- parted:
    device: "{{ partitionDevice }}"
    number: "{{ item.num }}"
    state: absent
  loop: "{{ info.partitions }}"
  when: hostvars['localhost'].repartition_device | bool and (item.num != 1 or item.fstype != 'ext4')
  name: "Removing extra partitions"

- parted:
    device: "{{ partitionDevice }}"
    state: present
    part_start: 0
    part_end: 100%
    label: gpt
    fs_type: ext4
    number: 1
  name: "Ensuring backup parition"
  when: hostvars['localhost'].repartition_device | bool

- pause:
    prompt: "Do you want to ensure ext4 on {{ partitionDevice }}1 (yes/no)?"
    register: format_device
    delegate_to: localhost

- filesystem:
    dev: "{{ partitionDevice }}1"
    fstype: ext4
    force: true
  name: "Ensuring ext4 filesystem"
  when: hostvars['localhost'].format_device | bool
